"""add_users_table

Revision ID: 2c13321fa03e
Revises: 
Create Date: 2026-09-21 17:02:23.417078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2c13321fa03e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='内部自增ID'),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False, comment='对外UUID'),
    sa.Column('phone', sa.String(length=11), nullable=False, comment='手机号(登录名)'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='bcrypt密码哈希'),
    sa.Column('nickname', sa.String(length=32), nullable=True, comment='显示名'),
    sa.Column('avatar_url', sa.String(length=255), nullable=True, comment='头像URL'),
    sa.Column('status', sa.Enum('active', 'disabled', name='user_status'), server_default='active', nullable=False, comment='状态'),
    sa.Column('role', sa.Enum('superadmin', 'user', name='user_role'), server_default='user', nullable=False, comment='平台角色'),
    sa.Column('token_version', sa.Integer(), server_default='0', nullable=False, comment='会话版本号'),
    sa.Column('gitlab_username', sa.String(length=64), nullable=True, comment='GitLab用户名'),
    sa.Column('gitlab_token_encrypted', sa.Text(), nullable=True, comment='AES-GCM加密的GitLab token'),
    sa.Column('gitlab_token_scopes', sa.JSON(), nullable=True, comment='GitLab token scope列表'),
    sa.Column('gitlab_token_bound_at', sa.DateTime(), nullable=True, comment='GitLab token绑定时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
